// constants/specializations.ts

export const SPECIALIZATIONS = [
  "Cardiology",
  "Dermatology",
  "Emergency Medicine",
  "Family Medicine",
  "General Surgery",
  "Internal Medicine",
  "Neurology",
  "Obstetrics & Gynecology",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Orthopedic Surgery",
  "Pediatrics",
  "Psychiatry",
  "Radiology",
  "Urology",
  "General Practice",
  "Endocrinology",
  "Gastroenterology",
  "Hematology",
  "Sports Medicine",
  "Rheumatology",
  "Psichiatry",
  "ENT",
  "Neonatology",
  "Plastic Surgery",
  "Pulmonology",
] as const;
